import { motion } from "framer-motion";
import { Sparkles, Newspaper, Rocket, Lightbulb, Brain, Gauge } from "lucide-react";
import { TypingText } from "../TypingText";
import { CountUp } from "../CountUp";

const insights = [
  {
    icon: Sparkles,
    tag: "Daily Insight",
    title: "Semiconductor sector entering accumulation phase",
    body: "AI models detect institutional accumulation across NVDA, AMD, and AVGO with combined confidence of 91%.",
    confidence: 91,
  },
  {
    icon: Newspaper,
    tag: "News Sentiment",
    title: "Fed dovish pivot drives tech rally",
    body: "Sentiment shift across 4,200 news sources turned positive (+0.68) following yesterday's FOMC minutes.",
    confidence: 84,
  },
  {
    icon: Rocket,
    tag: "Top Predicted Growth",
    title: "5 stocks projected to outperform S&P by 18%+",
    body: "PLTR, SMCI, MELI, CRWD, NOW lead our 30-day forecast leaderboard with sustained momentum signals.",
    confidence: 76,
  },
  {
    icon: Lightbulb,
    tag: "AI Suggestion",
    title: "Rebalance exposure toward defensive growth",
    body: "Current portfolio drift suggests reducing high-beta exposure by 12% and reallocating to quality compounders.",
    confidence: 88,
  },
];

const summary =
  "Markets opened strong with tech leading +1.8%. Semis show institutional accumulation (NVDA, AMD). Bond yields softened on dovish Fed minutes. Sentiment net-positive at +0.68 across 4,200 sources. Watch energy for late-day rotation.";

export function Insights() {
  return (
    <section id="insights" className="relative py-24">
      <div className="mx-auto max-w-7xl px-6">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-14 max-w-2xl"
        >
          <div className="mb-3 text-xs uppercase tracking-widest text-electric">AI Insights</div>
          <h2 className="font-display text-4xl font-semibold tracking-tight md:text-5xl">
            Daily intelligence,<br />
            <span className="text-gradient">delivered before the open.</span>
          </h2>
        </motion.div>

        {/* Daily AI summary panel */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="glass-card relative mb-6 overflow-hidden rounded-3xl p-7"
        >
          <div className="absolute -right-20 -top-20 h-60 w-60 rounded-full opacity-25 blur-3xl" style={{ background: "var(--gradient-electric)" }} />
          <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <div className="lg:col-span-2">
              <div className="flex items-center gap-3">
                <div className="grid h-10 w-10 place-items-center rounded-xl" style={{ background: "var(--gradient-electric)" }}>
                  <Brain className="h-5 w-5 text-primary-foreground" />
                </div>
                <div>
                  <div className="text-[10px] font-semibold uppercase tracking-widest text-electric">Pre-market briefing · 06:00 ET</div>
                  <div className="font-display text-lg font-semibold">Market summary, generated by Atlas-4</div>
                </div>
              </div>
              <p className="mt-5 text-base leading-relaxed text-foreground/85">
                <TypingText text={summary} speed={14} />
              </p>
            </div>

            <div className="flex flex-col justify-center gap-4">
              <Meter label="Bull / Bear Sentiment" value={72} accent="emerald" rightLabel="Bullish" />
              <Meter label="AI Confidence" value={89} accent="electric" rightLabel="High" />
              <Meter label="Volatility Regime" value={28} accent="electric" rightLabel="Calm" />
            </div>
          </div>
        </motion.div>

        <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
          {insights.map((ins, i) => {
            const Icon = ins.icon;
            return (
              <motion.div
                key={ins.title}
                initial={{ opacity: 0, y: 40 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: i * 0.1 }}
                className="glass-card group relative overflow-hidden rounded-3xl p-7"
              >
                <div className="absolute -right-20 -top-20 h-48 w-48 rounded-full opacity-20 blur-3xl transition-opacity duration-500 group-hover:opacity-40" style={{ background: "var(--gradient-electric)" }} />
                <div className="flex items-start gap-4">
                  <div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl" style={{ background: "var(--gradient-electric)" }}>
                    <Icon className="h-5 w-5 text-primary-foreground" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between gap-3">
                      <div className="text-[10px] font-semibold uppercase tracking-widest text-electric">{ins.tag}</div>
                      <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-muted-foreground">
                        <Gauge className="h-3 w-3" /> conf <span className="text-electric"><CountUp to={ins.confidence} suffix="%" /></span>
                      </div>
                    </div>
                    <h3 className="mt-1.5 font-display text-xl font-semibold leading-tight">{ins.title}</h3>
                    <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{ins.body}</p>
                    <div className="mt-4 h-1 overflow-hidden rounded-full bg-secondary">
                      <motion.div
                        initial={{ width: 0 }}
                        whileInView={{ width: `${ins.confidence}%` }}
                        viewport={{ once: true }}
                        transition={{ duration: 1.2, delay: 0.3, ease: "easeOut" }}
                        className="h-full rounded-full"
                        style={{ background: "var(--gradient-electric)" }}
                      />
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

function Meter({ label, value, accent, rightLabel }: { label: string; value: number; accent: "electric" | "emerald"; rightLabel: string }) {
  const grad = accent === "electric" ? "var(--gradient-electric)" : "var(--gradient-emerald)";
  const color = accent === "electric" ? "text-electric" : "text-emerald-trend";
  return (
    <div>
      <div className="mb-1.5 flex items-center justify-between text-xs">
        <span className="text-muted-foreground">{label}</span>
        <span className={`font-display ${color}`}>{rightLabel} · <CountUp to={value} /></span>
      </div>
      <div className="h-1.5 overflow-hidden rounded-full bg-secondary">
        <motion.div
          initial={{ width: 0 }}
          whileInView={{ width: `${value}%` }}
          viewport={{ once: true }}
          transition={{ duration: 1.4, ease: [0.22, 1, 0.36, 1] }}
          className="h-full rounded-full"
          style={{ background: grad, boxShadow: `0 0 10px ${accent === "electric" ? "var(--electric)" : "var(--emerald-trend)"}` }}
        />
      </div>
    </div>
  );
}
